### ISSUE TITLE
restrict permissions to /remove command 

### ISSUE THREAD

**Issue by joaorafaelm** [joaorafaelm/markov-bot#13]
might be a little dangerous to allow anyone other than the admins( from the env var) to delete all messages

**Comment by OneTrueBen** [comment]
So the chat admins should not have permission to use /remove? I can do this

**Comment by shadycake** [comment]
Do you mean to restrict the `/remove` command to only the env var admins (Not the chat admins)?

**Comment by joaorafaelm** [comment]
yes but i think there is a pr for this already

**Comment by AndreiRegiani** [comment]
Even for chat admins should have a confirmation, I just deleted our data by accident :(
