### ISSUE TITLE
Test fail

### ISSUE THREAD

**Issue by licensed** [joaorafaelm/markov-bot#263]
Melhor bot do mundo!
Estou tentando rodar ele aqui, mas não passa no último teste, e nem roda (quando dou o run, dá o mesmo erro)
>   return ['::'.join((w.text, w.pos_, w.dep_))
            for w in process_text(sentence)]
E   AttributeError: 'str' object has no attribute 'text'
markov/speech.py:65: AttributeError

FAILED test/test_speech.py::test_get_model - AttributeError: 'str' object has no attribute 'text'

Alguém tem idéia o que pode ser?

**Comment by julianolf** [comment]
Fala @licensed, tudo bem? 🙂

Esse problema está relacionado aos módulos de processamento de linguagem natural da biblioteca [Spacy](https://spacy.io/), que podem ser habilitados ou não.

Se habilitados eles melhoram a construção das mensagens.

Como esta funcionalidade é opcional os módulos não são instalados por padrão junto com  as dependências do projeto, você precisa definir quais linguagens (das suportadas pela biblioteca) você quer trabalhar e instalar manualmente os respectivos módulos.

Como exemplo, se você quiser habilitar o processamento para o idioma Português você poderia fazer o seguinte.

Abrir um terminal e digitar os seguintes comandos dentro do diretório raiz do projeto:
```sh
$ pipenv shell
$ python -m spacy download pt_core_news_sm
```

Em seguida editar seu arquivo `.env` que está no mesmo diretório configurando a variável `MODEL_LANG` para utilizar este módulo:
```sh
MODEL_LANG=pt_core_news_sm
```

Se estiver habilitando essa funcionalidade para mais de um idioma basta separar o nome dos módulos por vírgula.
```sh
MODEL_LANG=pt_core_news_sm,en_core_web_sm
```

Para saber mais detalhes sobre como instalar os módulos e quais idiomas são suportados da uma olhada nesse [link](https://spacy.io/usage/models).

E para desabilitar basta editar seu arquivo `.env` removendo a variável `MODEL_LANG`.

Espero que isso ajude.

PS.: Lembrando que isso é o suficiente para rodar os testes mas se quiser rodar o bot localmente ainda vai precisar adicionar seu token da API do Telegram no arquivo `.env` e rodar os comandos `make db && make migrate` antes do `make run`. 😉
