### ISSUE TITLE
generate messages at random

### ISSUE THREAD

**Issue by joaorafaelm** [joaorafaelm/markov-bot#3]

**Comment by adi44** [comment]
I would like to work

**Comment by joaorafaelm** [comment]
@adi44 Hi, thanks for the interest.
I have a snippet that could be a solution for this feature. 
It would also be nice to have a way to limit the amount of messages sent in a certain amount of time.
https://gist.github.com/joaorafaelm/c3754630b2eedefcdfdf9aa77f62bcd2

**Comment by adi44** [comment]
Pls brief me about the issue. What is required to do

**Comment by joaorafaelm** [comment]
@adi44 Ill close this issue, I dont think this feature will be nice :)
Created the https://github.com/joaorafaelm/markov-bot/issues/12 instead
